### ISSUE TITLE
GIMP missing various dependencies

### ISSUE THREAD

**Issue by Admicos** [eudaldgr/kiss-garbage#11]
From my testing:

- `babl` requires `gobject-introspection` and `vala`. (`gobject-introspection` is required somewhere in GIMP's dependency chain, but it gets installed after babl, which causes babl's build to fail.)
- `librsvg` requires `gdk-pixbuf` to generate a `GdkPixbuf-2.0.gir` file, which it doesn't. (Might be an issue on my end)

**Comment by eudaldgr** [comment]
* Fixed depends on `babl`.
 * You need to install `gdk-pixbuf` from this repo, not the one of official kisslinux repo, to have the `GdkPixbuf-2.0.gir`.
