### ISSUE TITLE
Inkscape has no icons

### ISSUE THREAD

**Issue by Muvkina** [eudaldgr/kiss-garbage#3]
I'm not sure if I am missing a package that I need to install. I installed adwaita-icon-theme thinking that was the issue however it wasn't. Any idea?

**Comment by eudaldgr** [comment]
Yeah i know that issue, but i have no idea what's missing

**Comment by Muvkina** [comment]
I have an idea to fix this I will test soon at my pc however we may be missing the default icons.svg.

**Comment by Muvkina** [comment]
That did not work.
