### ISSUE TITLE
New Package

### ISSUE THREAD

**Issue by Muvkina** [eudaldgr/kiss-garbage#7]
Hello, I was just wondering if I were to package this: [Pitivi](http://www.pitivi.org/) if you would be interested in it for this repo?

**Comment by eudaldgr** [comment]
Well, yes.

**Comment by eudaldgr** [comment]
If you want [this](https://github.com/eudaldgr/kiss-repo/tree/master/testing/pitivi), i have packaged some of their dependencies, you can see on the lasts commits, before `pitivi`.
